#!/usr/bin/bash

#   This function echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one foreground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).
#

function colors {
T='gYw'   # The test text

echo -e "\n                 40m     41m     42m     43m\
     44m     45m     46m     47m";

for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m';
  do FG=${FGs// /}
  echo -en " $FGs \033[$FG  $T  "
  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
  done
  echo;
done
echo
}

function paprika {
mpv 'http://82.76.249.81/digiedge2/tvpaprikaehq/index.m3u8?is=39&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function nature {
mpv 'http://82.76.249.81/digiedge2/viasatnatureehq/index.m3u8?is=42&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function tv1000 {
mpv 'http://82.76.249.81/digiedge2/tv1000hq/index.m3u8?is=42&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function digisport1 {
mpv 'http://82.76.249.81/digiedge/digisport1ehq/index.m3u8?is=1&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function digisport2 {
mpv 'http://82.76.249.81/digiedge/digisport2ehq/index.m3u8?is=2&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function digisport3 {
mpv 'http://82.76.249.81/digiedge/digisport3ehq/index.m3u8?is=3&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function digisport4 {
mpv 'http://82.76.249.81/digiedge/digisport4ehq/index.m3u8?is=49&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function eurosport {
#mpv 'http://82.76.249.81/digiedge2/eurosportehq/index.m3u8?is=31&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
mpv 'http://91.211.50.77:4011/udp/224.21.21.38:1234' >/dev/null 2>&1 &
echo
}

function eurosport2 {
mpv 'http://82.76.249.81/digiedge2/eurosport2ehq/index.m3u8?is=32&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function tvr1 {
mpv 'http://82.76.249.81/digiedge2/tvr1ehq/index.m3u8?is=24&src=digi-online.ro&t=0000000000000000000000000000000' >/dev/null 2>&1 &
echo
}

function tvr2 {
mpv 'http://82.76.249.81/digiedge2/tvr2ehq/index.m3u8?is=38&src=digi-online.ro&t=00000000000000000000000000000000' >/dev/null 2>&1 &
echo
}
